language: python
sudo: false
env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py36-flake8
  - TOX_ENV=py27-dj111
  - TOX_ENV=py36-dj111
  - TOX_ENV=py36-dj20
install:
 - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
